# Generated by Django 3.2.23 on 2024-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='location',
            field=models.CharField(choices=[('Church', 'Church'), ('Town Hall', 'Town Hall'), ('Venue', 'Venue'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
