# Generated by Django 3.2.23 on 2024-01-13 12:51

import cloudinary.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240112_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='inviter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bride', 'Bride'), ('groom', 'Groom')], default='Bride', max_length=11),
        ),
        migrations.AlterField(
            model_name='memories',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='memories',
            name='location',
            field=models.CharField(choices=[('Church', 'Church'), ('Town Hall', 'Town Hall'), ('Venue', 'Venue'), ('Other', 'Other')], max_length=20),
        ),
    ]
