# Generated by Django 3.2.23 on 2023-12-30 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20231229_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='inviter',
            field=models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom')], default='Bride', max_length=10),
        ),
        migrations.AddField(
            model_name='memories',
            name='location',
            field=models.CharField(choices=[('church', 'Church'), ('town_hall', 'Town Hall'), ('venue', 'Venue')], default='Venue', max_length=20),
        ),
        migrations.AddField(
            model_name='memories',
            name='people',
            field=models.ManyToManyField(related_name='other_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
