# Generated by Django 3.2.23 on 2024-01-17 12:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240113_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='inviter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bride', 'Bride'), ('Groom', 'Groom'), ('Both', 'Both')], default='Bride', max_length=16),
        ),
    ]
