# Generated by Django 3.2.23 on 2024-01-17 16:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_memories_inviter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='inviter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bride', 'Bride'), ('Groom', 'Groom')], max_length=11),
        ),
    ]
